apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmf-pvc
  namespace: newrelic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 100Mi